name: 语音合成引擎
package: cloud.lazycat.aipod.tts
version: 1.1.1
description: 支持多种语言的快速语音合成引擎
license: https://choosealicense.com/licenses/mit/
homepage:
author: x
locales:
  zh:
    name: "语音合成引擎"
    description: "支持多种语言的快速语音合成引擎"
  zh_CN:
    name: "语音合成引擎"
    description: "支持多种语言的快速语音合成引擎"
  en:
    name: "Text to Speech Engine"
    description: "Fast Text to Speech Engine with support for multiple languages"
  ja:
    name: "テキストから音声への変換エンジン"
    description: "複数の言語をサポートするテキストから音声への変換エンジン"
  ja_JP:
    name: "テキストから音声への変換エンジン"
    description: "複数の言語をサポートするテキストから音声への変換エンジン"
application:
  subdomain: tts
  routes:
      - /=http://caddy:80
  health_check:
    test_url: https://tts-ai.{{ .S.BoxDomain }}/health
    start_period: 1m

services:
  caddy:
    image: registry.lazycat.cloud/caddy:2.9.1-alpine
    setup_script: |
      cp /lzcapp/pkg/content/Caddyfile /etc/caddy/Caddyfile
